const accounts = [
  {
    id: 1,
    name: "TomJson",
    email: "TomJson@gamil.com",
    password: "TomJson1",
    created: new Date(),
  },
  {
    id: 2,
    name: "IssouDeter",
    email: "IssouDeter@gmail.com",
    password: "IssouDeter1",
    created: new Date(),
  },
  {
    id: 3,
    name: "JeanKrilin",
    email: "JeanKrilin@gmail.com",
    password: "JeanKrilin1",
    created: new Date(),
  },
  {
    id: 4,
    name: "GuerrierIndien",
    email: "GuerrierIndien@gmail.com",
    password: "GuerrierIndien",
    created: new Date(),
  },
  {
    id: 5,
    name: "35cmVeineux",
    email: "35cmVeineux@gmail.com",
    password: "35cmVeineux1",
    created: new Date(),
  },
  {
    id: 6,
    name: "GrandPorcMalade",
    email: "GrandPorcMalade@gmail.com",
    password: "GrandPorcMalade1",
    created: new Date(),
  },
  {
    id: 7,
    name: "Constiped",
    email: "Constiped@gmail.com",
    password: "Constiped1",
    created: new Date(),
  },
  {
    id: 8,
    name: "GenerationCelestin",
    email: "GenerationCelestin@gmail.com",
    password: "GenerationCelestin1",
    created: new Date(),
  },
  {
    id: 9,
    name: "KheyPolicier",
    email: "KheyPolicier@gmail.com",
    password: "KheyPolicier1",
    created: new Date(),
  },
  {
    id: 10,
    name: "MarwaLourde",
    email: "MarwaLourde@gmail.com",
    password: "MarwaLourde1",
    created: new Date(),
  },
  {
    id: 11,
    name: "HugoLeProlo",
    email: "HugoLeProlo@gmail.com",
    password: "HugoLeProlo1",
    created: new Date(),
  },
  {
    id: 12,
    name: "JulesVerge",
    email: "JulesVerge@gmail.com",
    password: "JulesVerge1",
    created: new Date(),
  },
];

module.exports = accounts;
